In [1]:
import numpy as np

In [2]:
a=np.matrix([[2, 10, -2], [3, 2, -2], [8, 14, -6]])

In [3]:
np.linalg.matrix_rank(a)

2

In [4]:
A=np.array([12, 8])

In [5]:
A_cent=A-A.mean()

In [6]:
A_st=A_cent/np.linalg.norm(A_cent)

In [7]:
v1=np.array([5, 1, 2])
v2=np.array([4, 2, 8])
print (np.corrcoef(v1, v2))

[[1.         0.05241424]
 [0.05241424 1.        ]]


In [8]:
import pandas as pd

In [9]:
x1=np.array([5.1, 1.8, 2.1, 10.3, 12.1, 12.6])

x2=np.array([10.2, 3.7, 4.1, 20.5, 24.2, 24.1])

x3=np.array([2.5, 0.9, 1.1, 5.1, 6.1, 6.3])


A=np.corrcoef([x1, x2, x3])

In [10]:
round(np.linalg.det(A), 7)

5e-07

In [11]:
A

array([[1.        , 0.99925473, 0.99983661],
       [0.99925473, 1.        , 0.99906626],
       [0.99983661, 0.99906626, 1.        ]])

In [12]:
round(np.linalg.det(Cor), 7)

NameError: name 'Cor' is not defined

# Полиномы

Для начала составим обычную матрицу наблюдений А, расположив векторы в столбцах. Обратите внимание, что вектор из 1 мы не будем добавлять в матрицу (за нас это сделает генератор полиномиальных признаков):

In [ ]:
A = np.array([
    [1, 3, -2, 1, 5, 13, 1],
    [3, 4, 5, -2, 4, 11, 3],
    [4, 5, 2, 2, 6, 8, -1],
]).T
print(A)

[[ 1  3  4]
 [ 3  4  5]
 [-2  5  2]
 [ 1 -2  2]
 [ 5  4  6]
 [13 11  8]
 [ 1  3 -1]]


Затем импортируем класс PolynomialFeatures из библиотеки sklearn. Создадим объект этого класса, указав при инициализации степень полинома равной 2. Также укажем, что нам нужна генерация столбца из 1 (параметр include_bias=True):

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2, include_bias=True)

Осталось только вызвать метод fit_transform() от имени этого объекта и передать в него нашу матрицу наблюдений . Для удобства выведем результат в виде DataFrame:

In [ ]:
A_poly = poly.fit_transform(A)
display(pd.DataFrame(A_poly))

0     1     2    3      4      5      6      7     8     9
0  1.0   1.0   3.0  4.0    1.0    3.0    4.0    9.0  12.0  16.0
1  1.0   3.0   4.0  5.0    9.0   12.0   15.0   16.0  20.0  25.0
2  1.0  -2.0   5.0  2.0    4.0  -10.0   -4.0   25.0  10.0   4.0
3  1.0   1.0  -2.0  2.0    1.0   -2.0    2.0    4.0  -4.0   4.0
4  1.0   5.0   4.0  6.0   25.0   20.0   30.0   16.0  24.0  36.0
5  1.0  13.0  11.0  8.0  169.0  143.0  104.0  121.0  88.0  64.0
6  1.0   1.0   3.0 -1.0    1.0    3.0   -1.0    9.0  -3.0   1.0

In [ ]:
X=np.array([[1, 3, -2, 9]]).T
y=np.array([3, 7, -5, 21])

In [ ]:
poly=PolynomialFeatures(degree=2, include_bias=True)
X_poly=poly.fit_transform(X)

In [ ]:
w_hat=np.linalg.inv(X_poly.T@X_poly)@X_poly.T@y

In [ ]:
round(w_hat[2], 1)

-0.0

In [27]:
A = np.array([
    [1, 1, 1, 1, 1],
    [5, 9, 4, 3, 5],
    [15, 18, 18, 19, 19],
    [7, 6, 7, 7, 7]
]).T
y = np.array([24, 22, 35, 33, 36])
E = np.eye(4)
# коэффициент регуляризации
alpha = 1


In [28]:
# получаем оценку коэффициентов регрессии по МНК с регуляризацией Тихонова
w_hat_ridge = np.linalg.inv(A.T@A+alpha*E)@A.T@y
print(np.round(w_hat_ridge, 2))

[-0.09 -1.71  1.91  0.73]
