In [1]:
import pandas as pd

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

In [2]:
Hut_Paradise_values = Hut_Paradise_DF.values

In [3]:
Hut_Paradise_values[4]

array([40, 33,  1,  6, 20, 16], dtype=int64)

In [4]:
Hut_Paradise_values[:, 3]

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5], dtype=int64)

In [5]:
Hut_Paradise_values[:, 1]-Hut_Paradise_values[:, 5]

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

In [6]:
import numpy as np

In [7]:
time=np.array([10,20,30,15,5,40,20,8,20])
print(Hut_Paradise_values[:,4] @ time)

1348


In [8]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [9]:
x=2*v+(-3)*w

In [10]:
x@u

0

In [11]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

In [12]:
Inc=np.array([Husband_Income, Wife_Income, Mother_In_Law_Income])

In [13]:
Inc=Inc.T

In [14]:
Inc

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

In [15]:
Cons=np.array([Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption])

In [16]:
Cons=Cons.T

In [17]:
Cons

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

In [18]:
Inc=0.87*Inc

In [19]:
Inc

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

In [20]:
R=Inc-Cons
print (R)

[[ 37.   30.5 -21.7]
 [141.4  94.   49.6]
 [ 61.8 -26.9 -53. ]]


In [21]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

In [22]:
A@x

array([26, 30])

In [23]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
B@A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [24]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

In [25]:
A=np.array([x, y, z])
Gr=A.T@A
print (Gr)

[[ 6  3  0  2  4]
 [ 3  6  0  1  8]
 [ 0  0  3 -1  4]
 [ 2  1 -1  1  0]
 [ 4  8  4  0 16]]


In [26]:
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

In [27]:
P=Price_DF.values
C=Count_DF.values

In [28]:
C

array([[10,  5, 12, 15, 10],
       [ 2, 21,  3, 25,  6],
       [12, 12,  0, 30,  4],
       [ 4,  8, 18, 14,  5],
       [ 6, 25, 27, 25, 18],
       [10,  3,  2, 17, 12],
       [22,  1,  4, 25, 20],
       [ 7,  0, 31, 31, 28]], dtype=int64)

In [29]:
P

array([[2. , 1.5, 1. , 0.8, 1. ],
       [1.8, 2.5, 1. , 1. , 1. ],
       [2. , 2. , 0. , 0.5, 2. ],
       [1.8, 1.2, 2.8, 0.8, 2. ],
       [2.5, 3.5, 2. , 1. , 1.5],
       [5. , 5. , 3. , 2. , 2.5],
       [1.1, 1. , 1.5, 0.5, 1.7],
       [4.5, 4. , 2.5, 1. , 2. ]])

In [30]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

In [31]:
P*C@com

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [32]:
P = Price_DF.values
C = Count_DF.values
styl_inc = (P*C)@(np.ones(5)-com)
print(styl_inc)

[ 50.2   74.88  59.1   67.8  166.6  113.8   66.21 157.75]


In [33]:
A=np.matrix('2, 0, 0; 0, 1, 0; 0, 0, 4')
np.linalg.det(np.linalg.inv(A))

0.12500000000000003

In [34]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])

In [35]:
np.linalg.inv(A)

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

In [36]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

In [37]:
v=np.array([v1, v2, v3, v4])

In [38]:
np.linalg.matrix_rank(v.T)

4

In [43]:
v.T@v

array([[110,  78,  82,  78,  81],
       [ 78, 116,  58,  74, 106],
       [ 82,  58,  83,  51,  71],
       [ 78,  74,  51,  67,  75],
       [ 81, 106,  71,  75, 114]])

In [44]:
g=v@v.T

In [46]:
round(np.linalg.det(g))

3716648

In [47]:
np.linalg.inv(g)


array([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
       [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
       [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
       [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])